name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Get runner IP
        run: echo "RUNNER_IP=$(curl ifconfig.me)" >> $GITHUB_ENV
        shell: bash

      - name: Whitelist IP
        env:
          MONGO_API_PUBLIC: ${{secrets.MONGO_API_PUBLIC}}
          MONGO_API_PRIVATE: ${{secrets.MONGO_API_PRIVATE}}
          MONGODB_PROJECT_ID: ${{secrets.MONGODB_PROJECT_ID}}
        run: |
          curl --location "https://cloud.mongodb.com/api/atlas/v1.0/groups/$MONGODB_PROJECT_ID/accessList" \
          --digest -u "$MONGO_API_PUBLIC:$MONGO_API_PRIVATE" \
          --header "Content-Type: application/json" \
          --data '[
            {
              "ipAddress": "'$RUNNER_IP'/32",
              "comment": "Added via GitHub db-update action"
            }
          ]'
        shell: bash


      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests
        run: pytest --cov --cov-report=xml

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Remove IP
        env:
          MONGO_API_PUBLIC: ${{secrets.MONGO_API_PUBLIC}}
          MONGO_API_PRIVATE: ${{secrets.MONGO_API_PRIVATE}}
          MONGODB_PROJECT_ID: ${{secrets.MONGODB_PROJECT_ID}}
        run: |
          curl --request DELETE \
          --location "https://cloud.mongodb.com/api/atlas/v1.0/groups/$MONGODB_PROJECT_ID/accessList/${RUNNER_IP}%2F32" \
          --digest -u "$MONGO_API_PUBLIC:$MONGO_API_PRIVATE"
        shell: bash